apiVersion: batch/v1
kind: Job
metadata:
  name: builder-job
  namespace: cforge
spec:
  template:
    spec:
      containers:
      - name: builder
        image: ghcr.io/stenius/cforge/builder:latest
        args:
        - https://github.com/laristra/c-makefile.git
      restartPolicy: Never
  backoffLimit: 2
