apiVersion: apps/v1
kind: Deployment
metadata:
  name: cforge-server
  namespace: cforge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cforge-server
  template:
    metadata:
      labels:
        app: cforge-server
    spec:
      serviceAccountName: server
      containers:
      - name: server
        image: ghcr.io/stenius/cforge/server:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
