apiVersion: v1
kind: ServiceAccount
metadata:
  name: server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: server-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: server-role-binding
subjects:
- kind: ServiceAccount
  name: server
  namespace: default
roleRef:
  kind: Role
  name: server-role
  apiGroup: rbac.authorization.k8s.io

